### PR TITLE
Fix quote_ident(regclass)

### PR DESCRIPTION
**Pull request by memoz**
https://github.com/2ndQuadrant/audit-trigger/issues/14

Added type cast to TEXT.

### CODE REVIEW

**Comment by memoz** [comment]
@ringerc Hope this doesn't break anything...This audit feature works quite well by the way.  :)

**Comment by ringerc** [comment]
Thanks. I'm glad to hear that. I wrote it years ago and extracted it from the project it was in because I thought it might be useful to others.

These days I'd probably use json storage, but back then hstore was the only option.

**Comment by nineinchnick** [comment]
Let me just reference my PR #12 with jsonb as a shameless plug.

**Comment by ringerc** [comment]
@nineinchnick I can't merge that as-is, since it'll break every existing user. I think it'd make sense to wrap it up as a proper extension - a subdir with its own Makefile, .control file, and extension SQL - instead of just replacing the existing file.

**Comment by nineinchnick** [comment]
@ringerc i know, i'm just referencing it for other people to check it out, maybe somebody would like to try it. Sorry if it's not appropriate.

**Pull request merged**
