### PR TITLE
Just converted from hstore to jsonb

### PR DESCRIPTION
**Pull request by michelmilezzi**
- Removed hstore dependency;
- Using jsonb builtin type;
- Postgres 10+.

### CODE REVIEW

**Comment by jackhamburger** [comment]
Is actively managing this project?

**Comment by jackhamburger** [comment]
@michelmilezzi Did you run into an issue with PG10 that hstore broke? 
Or is this removing a unneeded dependency made obsolete by jsonb?

**Comment by michelmilezzi** [comment]
Just removing a unneeded dependency. There's a long time since last activity here, I guess the folks from 2ndQuadrant discontinued this project...

**Comment by ringerc** [comment]
Moving to jsonb is wise. I'd like to find the time to test and merge this.

It'd be a huge help if you could prepare a test script we could replay to test the extension. One that:

* creates tables with sensible and `"sill 'y' "` names in the public schema
* creates a schema with sensible and `"difficult "" names"` and puts some tables in there
* creates the triggers
* runs some DML
* queries the results
* diffs the output vs an expected file

A simple way to do this would be to add a PGXS `Makefile` and a `sql/` and `expected/` directory so you could `make check`, treating it as a PostgreSQL extension. Bonus points for a control file etc.

I will not have time to do this. I can't really merge the jsonb change without some kind of test script but I can't find the time to write one either, so I'm going to have to ask if anyone else @ here is willing.

As for maintenance. This is not and never was a maintained product. It was my personal script I published for others, and re-hosted onto 2ndQ's account later. Like anything else you can contact info@2ndquadrant.com if you're interested in special arrangements, consulting etc. But really this is here as a service to the community because it's better here than on a wiki.

**Comment by phryneas** [comment]
Hey @michelmilezzi, are you still on this? Would be great to see this merged :)

**Comment by michelmilezzi** [comment]
@phryneas yes, buddy. I'll finish it asap

**Comment by sta-szek** [comment]
> * Postgres 10+.

@michelmilezzi hi.
You said postgres 10+, why?

I can see jsonb is also in Postgres 9.6 -- which I am using (cannot upgrade).
I wanted to switch to jsonb to improve my performance.

Is there anything I need to know about it? 
Thanks

**Comment by sta-szek** [comment]
I tried that on my local 9.6 (hstore works) and it throws exception:

```
Error inserting mock data: SQL Error [42883]: Batch entry 0 INSERT INTO ... VALUES ... was aborted: ERROR: operator does not exist: jsonb - text[]
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Where: PL/pgSQL function cdc.change_data_capture() line 54 at assignment  Call getNextException to see other errors in the batch.
```

**Comment by sta-szek** [comment]
I made it working by removing `- excluded_cols;` from all the places as I don't need this feature.

After testing it turned out that JSONB (at least in 9.6) is ~ 2 times slower than `hstore`.

10,000 records in table with 69 fields + 7 indices:
query: `update activity set "timestamp"=CURRENT_TIMESTAMP;`
1. no triggers: ~800ms
2. hstore: ~2,5s
3. jsonb: ~4,5s

Just FYI

**Comment by DavidBoone** [comment]
I also noticed the performance hit when switching from `hstore` to `jsonb`.  I was able to recover most of that performance by using `hstore` to calculated changed_fields, then converting that result to `jsonb`.  You can find that modification at https://github.com/michelmilezzi/audit-trigger/pull/1 or https://github.com/2ndQuadrant/audit-trigger/compare/master...DavidBoone:master

**Comment by trnl** [comment]
@sta-szek, @DavidBoone, @ringerc, are there any chance it will be merged?

**Comment by iloveitaly** [comment]
@2ndquadrant-ci any chance we could get this merged?

**Comment by ringerc** [comment]
No, I won't merge this PR, as it incompatibly changes the existing definition.

I would be happy to accept a PR that adds a json-flavoured extension with the same functionality, but you might as well just host your own and ask me to link to that instead of rewriting this one in that case.

**Pull request closed without merging**
