### PR TITLE
Replaced hstore with jsonb

### PR DESCRIPTION
**Pull request by nineinchnick**
Maybe this could be merged as a second `audit_json.sql` file.

### CODE REVIEW

**Comment by ringerc** [comment]
Interesting thought, but given that 9.4 is the oldest release with jsonb, not merging as it stands.

Creating an alternate variant would be reasonable.

**Comment by nineinchnick** [comment]
I was expecting that. I just wanted to leave a trail to such implementation if anybody would be looking for it.

**Comment by ringerc** [comment]
Good plan.

If you wrap it up with a suitable extension control file I'll fork this version off into a legacy branch and replace master with a jsonb-ified version.

**Comment by fosils** [comment]
This would have been great if there was a migration script from hstore to jsonb?

**Pull request closed without merging**
